FROM --platform=linux/amd64 node:18-alpine

WORKDIR /app

# パッケージ管理ファイルをコピー
COPY package*.json ./

# bcryptの代わりにbcryptjsを使用
RUN npm uninstall bcrypt || true
RUN npm install bcryptjs

# 依存関係のインストール
RUN npm install

# ソースコードのコピー
COPY . .

# Prisma Clientの生成
RUN npx prisma generate

# 開発サーバーの起動
CMD ["npm", "run", "dev"]
